# Generated by Django 2.0.1 on 2018-11-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hospital_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
