# Generated by Django 2.0.1 on 2018-11-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_auto_20181116_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('IP', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('balance_due', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
