# Generated by Django 2.0.1 on 2018-11-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_patient_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient_Details',
            new_name='Patient_Detail',
        ),
    ]
