# Generated by Django 2.0.1 on 2018-11-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20181118_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_detail',
            old_name='user',
            new_name='LabUser',
        ),
    ]
