# Generated by Django 2.0.1 on 2018-11-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20181118_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_detail',
            name='user_email',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
