# Generated by Django 2.0.1 on 2018-11-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_patient_detail_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_detail',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('undefined', 'Undefined')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
