# Generated by Django 2.0.1 on 2018-11-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_detail',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
    ]
