# Generated by Django 2.0.1 on 2018-11-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20181120_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('causes', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('prevention', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
