# Generated by Django 2.0.1 on 2019-11-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20181125_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=50)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
