# Generated by Django 2.0.1 on 2019-11-11 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0028_blood_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_sample',
            old_name='Description',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='blood_sample',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blood_sample',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blood_sample',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blood_sample',
            name='user_email',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='blood_sample',
            name='blood_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
