# Generated by Django 2.0.1 on 2019-11-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20191111_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_button',
            name='user',
        ),
    ]
