# Generated by Django 2.0.1 on 2019-11-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_request_button_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request_button',
            new_name='Request',
        ),
    ]
