# Generated by Django 2.0.1 on 2019-11-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20191111_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Request_button',
        ),
    ]
