# Generated by Django 2.0.1 on 2019-11-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20191111_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
