# Generated by Django 2.0.1 on 2019-11-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_delete_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medical_Library',
        ),
    ]
